# This is needed for the GitHub Action
api_token_env: CROWDIN_PERSONAL_TOKEN

project_id: "467866"

preserve_hierarchy: true
files:
  - source: "/MastodonSDK/Sources/MastodonLocalization/Resources/*.xcstrings"
    translation: "/MastodonSDK/Sources/MastodonLocalization/Resources/%file_name%.xcstrings"
    multilingual: true

  #- source: "/MastodonIntent/en.lproj/Intents.strings"
  #  translation: "/Localization/StringsConvertor/Intents/input/%osx_code%/%original_file_name%"

  #- source: "/MastodonIntent/en.lproj/Intents.stringsdict"
  #  translation: "/Localization/StringsConvertor/Intents/input/%osx_code%/%original_file_name%"

  #- source: "/Localization/ios-infoPlist.json"
  #  translation: "/Localization/StringsConvertor/input/%osx_code%/%original_file_name%"
