#
# Files configuration
#
files: [
 {
  # App info plist strings template
  "source" : "/Localization/ios-infoPlist.json",
  "translation" : "/Localization/StringsConvertor/input/%osx_code%/%original_file_name%",
  "update_option" : "update_as_unapproved",
 },
 {
  # App xcstrings
  "source" : "/MastodonSDK/Sources/MastodonLocalization/Resources/Localizable.xcstrings",
  "translation" : "/MastodonSDK/Sources/MastodonLocalization/Resources/Localizable.xcstrings",
  "multilingual" : "true"
  # "update_option" : "update_as_unapproved",
 },
 {
  # intents strings
  "source" : "/MastodonIntent/en.lproj/Intents.strings",
  "translation" : "/Localization/StringsConvertor/Intents/input/%osx_code%/%original_file_name%",
  # "update_option" : "update_as_unapproved",
 },
 {
  # intents strings dict
  "source" : "/MastodonIntent/en.lproj/Intents.stringsdict",
  "translation" : "/Localization/StringsConvertor/Intents/input/%osx_code%/%original_file_name%",
  # "update_option" : "update_as_unapproved",
 },
]
