lane :app_size do
    emerge(
        file_path: "./build/Archives/#{ENV['SCHEME']}.xcarchive",
        repo_name: ENV['GITHUB_REPOSITORY'],
        sha: ENV['GITHUB_SHA'],
        base_sha: "git SHA",
    )
end