name: Crowdin / Upload translations

on:
  push:
    branches:
      - "develop"
    paths:
      - MastodonSDK/Sources/MastodonLocalization/Resources/*.xcstrings
      - MastodonIntent/en.lproj/Intents.strings
      - MastodonIntent/en.lproj/Intents.stringsdict
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload-translations:
    runs-on: ubuntu-latest
    if: github.repository == 'mastodon/mastodon-ios'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          crowdin_branch_name: ${{ github.base_ref || github.ref_name }}

        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
